language: python

matrix:
  include:
    - os: linux
      sudo: true

services:
  - docker
  
before_install:
  - echo "before install..."
  - docker pull schickling/octave
  - docker ps -a
  
addons:
  apt:
    update: true
